Extend player.takedamage function (Adding an optional hitnumber parameters) + Feral Attack Optimization(?) - Shirane
Ormael13/CoCX pull request #593
Opened 2023-11-28 16:06 UTC by shmuphead

player.takedamage() adds optional hit parameter (default 1), allows multiple hit proc and should be backward compatible
ExtraNaturalWeaponPrep() before repeatedly calling ExtraNaturalWeaponAttack() to save some overhead from repeatedly check for same shit

quite a bit of change so DM me on discord if theres problem with it

2023-11-28 23:38 UTC, jfmherokiller requested changes

2023-11-28 23:38 UTC, jfmherokiller commented on classes/classes/Scenes/Dungeons/EbonLabyrinth/EyeTyrant.as
> +		private function eyeTyrantOmnicastD():void {
remove this extra definition

2023-11-29 15:00 UTC, shmuphead commented
Ok this one is pretty big change I will admit and I am not really familiar with making a separate fork so yeah
Adding override functions for attack() Yeah no more fucking bazillion is monster checks

Added override method: preAttackSeal(), preAttack(), midAttackSkip(), midAttackSeal(), midDodge(), postDodge()

2023-11-29 15:29 UTC, jfmherokiller requested changes
some extranious comment removal

2023-11-29 20:43 UTC, merged